language: android
jdk: oraclejdk8
android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.3
    - android-25
    - extra-android-m2repository
before_install:
 - chmod +x gradlew
env:
 - GRADLE_OPTS="-Xmx512m -XX:MaxPermSize=512m"
after_success:
 - ./gradlew assemble
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
deploy:
  provider: script
  script: ./gradlew bintrayUpload -PdryRun=false
  skip_cleanup: true
  on:
    tags: true
    branch: /^v\d+\.\d+\.\d+$/
branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+$/