language: android
jdk: oraclejdk8
android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.3
    - android-25
    - extra-android-m2repository
before_install:
 - chmod +x gradlew
env:
 - GRADLE_OPTS="-Xmx512m -XX:MaxPermSize=512m"
after_success:
 - ./gradlew assemble
deploy:
  provider: script
  script: ./gradlew clean
  skip_cleanup: true
  on:
    tags: true
branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+$/